Ag 6/display expired key error
slovensko-digital/autogram pull request #190
Opened 2023-05-25 08:42 UTC by Bombino1024

2023-05-25 09:32 UTC, jsuchal requested changes

2023-05-25 09:32 UTC, jsuchal commented on src/test/java/digital/slovensko/autogram/core/SigningCertificateExpiredMessagePredicateTest.java
> +package digital.slovensko.autogram.core;
Kedze mas tie testy dole vysokourovnove, toto mi pride zbytocne testovat.

2023-05-25 09:32 UTC, jsuchal commented on src/main/java/digital/slovensko/autogram/core/Autogram.java
> +                        -> ui.onSigningFailed(AutogramException.createFromIllegalArgumentException(e)));
```suggestion
                ui.onUIThreadDo(()
                -> ui.onSigningFailed(AutogramException.createFromIllegalArgumentException(e)));
```

2023-05-25 09:32 UTC, jsuchal commented on src/main/java/digital/slovensko/autogram/core/errors/AutogramException.java
> +                if (new SigningCertificateExpiredMessagePredicate().test(cause.getMessage())) {
Rozumiem co robis, ale toto mi pride predcasna abstrakcia na predikat, normalne by som ten REGEX dal ako konstatnu a tuto to otestoval priamo je to oneliner, vyrabat kvoli tomu triedu mi pride zbytocne, specialne ked sa nikde inde nepouzije.

2023-05-25 09:32 UTC, jsuchal commented on src/main/java/digital/slovensko/autogram/core/errors/SigningWithExpiredCertificateException.java
> +        super("Nastala chyba", "Platnosť podpisového certifikátu vypršala", "Certifkát v čase podpisu nie je platný.\n\nProsím zmente podpisový certifkát.");
```suggestion
        super("Nastala chyba", "Platnosť podpisového certifikátu vypršala", "Certifkát už nie je platný.\n\nPravdepodobne budete musieť získať nový a platný certifikát.");
```

2023-05-25 09:32 UTC, jsuchal commented on src/test/java/digital/slovensko/autogram/AutogramTests.java
> +            mockedStatic.when(TokenDriver::getAvailableDrivers).thenReturn(Arrays.asList(new FakeTokenDriver("fake")));
Toto smrdi tym, ze nam tu chyba nejake injektovanie objektu co odpoveda na `getAvailableDrivers`. Mozno by sme to mohli posielat do autogramu ako optional parameter v konstruktore, nasledne tam len posles mock a nemusis mockovat vnutornosti. Hm?

2023-05-29 13:47 UTC, jsuchal commented on src/test/java/digital/slovensko/autogram/core/errors/AutogramExceptionTest.java
> +}
```suggestion
}

```

2023-05-30 12:00 UTC, Bombino1024 commented
@jsuchal Review poprosim, nejde mi pridat reviewera

2023-05-30 12:09 UTC, Bombino1024 commented
@jsuchal Uz vidim

2023-05-31 11:39 UTC, jsuchal commented
@Bombino1024 inak skusil som ti pridat nejake prava, mozno ti uz pojdu tie request review na mna.

2023-05-31 13:03 UTC, merged